///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace CalculatorMinus
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the CalculatorRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("2c677167-62c4-41f9-b26c-48f694d3be10")]
    public partial class CalculatorRepository : RepoGenBaseFolder
    {
        static CalculatorRepository instance = new CalculatorRepository();

        /// <summary>
        /// Gets the singleton class instance representing the CalculatorRepository element repository.
        /// </summary>
        [RepositoryFolder("2c677167-62c4-41f9-b26c-48f694d3be10")]
        public static CalculatorRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public CalculatorRepository() 
            : base("CalculatorRepository", "/", null, 0, false, "2c677167-62c4-41f9-b26c-48f694d3be10", ".\\RepositoryImages\\CalculatorRepository2c677167.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("2c677167-62c4-41f9-b26c-48f694d3be10")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class CalculatorRepositoryFolders
    {
    }
#pragma warning restore 0436
}
