///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace CalculatorMinus
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the CloseCalcualtorAppRecordingRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("f7900d67-93df-4ce1-9060-ac6bf207f487")]
    public partial class CloseCalcualtorAppRecordingRepository : RepoGenBaseFolder
    {
        static CloseCalcualtorAppRecordingRepository instance = new CloseCalcualtorAppRecordingRepository();
        CloseCalcualtorAppRecordingRepositoryFolders.CalculatorAppFolder _calculator;

        /// <summary>
        /// Gets the singleton class instance representing the CloseCalcualtorAppRecordingRepository element repository.
        /// </summary>
        [RepositoryFolder("f7900d67-93df-4ce1-9060-ac6bf207f487")]
        public static CloseCalcualtorAppRecordingRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public CloseCalcualtorAppRecordingRepository() 
            : base("CloseCalcualtorAppRecordingRepository", "/", null, 0, false, "f7900d67-93df-4ce1-9060-ac6bf207f487", ".\\RepositoryImages\\CloseCalcualtorAppRecordingRepositoryf7900d67.rximgres")
        {
            _calculator = new CloseCalcualtorAppRecordingRepositoryFolders.CalculatorAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("f7900d67-93df-4ce1-9060-ac6bf207f487")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Calculator folder.
        /// </summary>
        [RepositoryFolder("6d956e89-a807-46b2-be46-cb4d8abd2b4d")]
        public virtual CloseCalcualtorAppRecordingRepositoryFolders.CalculatorAppFolder Calculator
        {
            get { return _calculator; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class CloseCalcualtorAppRecordingRepositoryFolders
    {
        /// <summary>
        /// The CalculatorAppFolder folder.
        /// </summary>
        [RepositoryFolder("6d956e89-a807-46b2-be46-cb4d8abd2b4d")]
        public partial class CalculatorAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _closeInfo;

            /// <summary>
            /// Creates a new Calculator  folder.
            /// </summary>
            public CalculatorAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Calculator", "/winapp[@packagename='Microsoft.WindowsCalculator']", parentFolder, 30000, null, true, "6d956e89-a807-46b2-be46-cb4d8abd2b4d", "")
            {
                _closeInfo = new RepoItemInfo(this, "Close", "?/?/button[@automationid='Close']", "?/?/button[@automationid='Close']", 30000, null, "6cc0f988-6fd9-4bfd-81ed-5f9b2e904a71");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("6d956e89-a807-46b2-be46-cb4d8abd2b4d")]
            public virtual Ranorex.WindowsApp Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WindowsApp>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("6d956e89-a807-46b2-be46-cb4d8abd2b4d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Close item.
            /// </summary>
            [RepositoryItem("6cc0f988-6fd9-4bfd-81ed-5f9b2e904a71")]
            public virtual Ranorex.Button Close
            {
                get
                {
                    return _closeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Close item info.
            /// </summary>
            [RepositoryItemInfo("6cc0f988-6fd9-4bfd-81ed-5f9b2e904a71")]
            public virtual RepoItemInfo CloseInfo
            {
                get
                {
                    return _closeInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
